theme: minima
title: github pages with componatus
author: GitHub User
email: t.hanrong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning how to write html is fun!
  
# social links
twitter_username: take-your-pick # DO NOT include the @ character, or else the build will fail!
github_username:  componatus # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
